#!/bin/zsh

REQUIRED_SWIFTLINT_VERSION='0.45.0'

if ! type swiftlint > /dev/null; then
  echo "swiftlint not installed, exiting..."
  exit 1
fi

CURRENT_SWIFTLINT_VERSION=$(swiftlint --version)

if [ $CURRENT_SWIFTLINT_VERSION != $REQUIRED_SWIFTLINT_VERSION ]; then
    echo "swiftlint required version $REQUIRED_SWIFTLINT_VERSION, current version $CURRENT_SWIFTLINT_VERSION"
	exit 1
else
    swiftlint lint $1
fi
